Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'test/**/*'

Lint/RedundantCopDisableDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods:
    - namespace
    - attributes_table
    - configure
    - params
    - with
    - requires
    - optional
    - route_param
    - resource

Metrics/ClassLength:
  Exclude:
    - app/api/**/*
